config-version: 2
name: 'fivetran_log'
version: '2.3.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]

models:
  fivetran_log:
    +materialized: table
    +schema: fivetran_platform
    staging:
      +schema: stg_fivetran_platform
      +materialized: view

vars:
  fivetran_log:
    account: "{{ source('fivetran_platform', 'account') }}"
    incremental_mar: "{{ source('fivetran_platform', 'incremental_mar') }}"
    connection: "{{ source('fivetran_platform', 'connection') }}"
    connector: "{{ source('fivetran_platform', 'connector') }}"
    credits_used: "{{ source('fivetran_platform', 'credits_used') }}"
    destination: "{{ source('fivetran_platform', 'destination') }}"
    destination_membership: "{{ source('fivetran_platform', 'destination_membership') }}"
    log: "{{ source('fivetran_platform', 'log') }}"
    user: "{{ source('fivetran_platform', 'user') }}"
    usage_cost: "{{ source('fivetran_platform', 'usage_cost') }}"
    transformation_runs: "{{ source('fivetran_platform','transformation_runs') }}"
