config-version: 2
name: 'fivetran_log'
version: '0.7.5'
require-dbt-version: [">=1.3.0", "<2.0.0"]

models:
  fivetran_log:
    +materialized: table
    +schema: fivetran_log
    staging:
      +schema: stg_fivetran_log
      tmp:
        +materialized: view

vars:
  fivetran_log:
    account: "{{ source('fivetran_log', 'account') }}"
    account_membership: "{{ source('fivetran_log', 'account_membership') }}"
    incremental_mar: "{{ source('fivetran_log', 'incremental_mar') }}"
    connector: "{{ source('fivetran_log', 'connector') }}"
    credits_used: "{{ source('fivetran_log', 'credits_used') }}"
    destination: "{{ source('fivetran_log', 'destination') }}"
    destination_membership: "{{ source('fivetran_log', 'destination_membership') }}"
    log: "{{ source('fivetran_log', 'log') }}"
    transformation: "{{ source('fivetran_log', 'transformation') }}"
    trigger_table: "{{ source('fivetran_log', 'trigger_table') }}"
    user: "{{ source('fivetran_log', 'user') }}"
    usage_cost: "{{ source('fivetran_log', 'usage_cost') }}"
