#!/bin/bash
curl -s -o /tmp/build_setup.sh "https://raw.githubusercontent.com/fivetran/dbt_package_automations/refs/heads/feature/buildkite-scripts/.buildkite/scripts/build_setup.sh"
source /tmp/build_setup.sh